# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ftutils', [dirname(__file__)])
        except ImportError:
            import _ftutils
            return _ftutils
        if fp is not None:
            try:
                _mod = imp.load_module('_ftutils', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ftutils = swig_import_helper()
    del swig_import_helper
else:
    import _ftutils
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


FT_DB_SUCCESS = _ftutils.FT_DB_SUCCESS
FT_DB_ENTRY_EXISTS = _ftutils.FT_DB_ENTRY_EXISTS
FT_DB_FULL = _ftutils.FT_DB_FULL
FT_DB_INVALID_PARAM = _ftutils.FT_DB_INVALID_PARAM
FT_DB_ENTRY_DOESNOTEXIST = _ftutils.FT_DB_ENTRY_DOESNOTEXIST

def ft_db_insert(*args):
  return _ftutils.ft_db_insert(*args)
ft_db_insert = _ftutils.ft_db_insert

def ft_db_init(*args):
  return _ftutils.ft_db_init(*args)
ft_db_init = _ftutils.ft_db_init

def ft_db_find_by_key(*args):
  return _ftutils.ft_db_find_by_key(*args)
ft_db_find_by_key = _ftutils.ft_db_find_by_key

def ft_db_find_by_hndl(*args):
  return _ftutils.ft_db_find_by_hndl(*args)
ft_db_find_by_hndl = _ftutils.ft_db_find_by_hndl

def ft_db_remove_by_key(*args):
  return _ftutils.ft_db_remove_by_key(*args)
ft_db_remove_by_key = _ftutils.ft_db_remove_by_key

def ft_db_remove_by_hndl(*args):
  return _ftutils.ft_db_remove_by_hndl(*args)
ft_db_remove_by_hndl = _ftutils.ft_db_remove_by_hndl


